# Default values for vault-actions.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
devDebug: false

image:
  repository: ghcr.io/jr200/vault-actions
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

secretPathOverride: ""
secretName: ""

config:
  vault:
    url: http://vault.vault.svc
    token: ~

  bootstrap:
    cleanup_after_install: true
    params:
      display-name: vault-actions-bootstrap
      explicit-max-ttl: 5m
      renewable: false
      wrap-ttl: 120s
      format: table
      field: wrapping_token

  actions: []
    # - path: sys/policy/test-app-policy
    #   type: write
    #   params:
    #     - k: policy
    #       v: |
    #         path "kv/data/test-app/db" {
    #           capabilities = ["read"]
    #         }

    #         path "kv/data/test-app/mq" {
    #           capabilities = ["read"]
    #         }

    # - path: auth/kubernetes/role/test-app-role
    #   type: write
    #   params:
    #     - { k: bound_service_account_names, v: test-app-service-account }
    #     - { k: bound_service_account_namespaces, v: test-app-namespace }
    #     - { k: policies, v: test-app-policy }
    #     - { k: ttl, v: 1h }

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

hookConfiguration:
  hook: pre-install
  hookWeight: -5
  hookDeletePolicy: before-hook-creation,hook-succeeded

podAnnotations: {}
podLabels: {}

## Optionally specify extra environment variables to add to container
extraEnv:
  - name: VAULT_CLIENT_TIMEOUT
    value: "30"

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
