# if an alternative secret was not been provided,
# construct a default app config from the values.yaml
{{- if not .Values.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vault-actions.fullname" . }}
  labels: {{- include "vault-actions.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": {{ .Values.hookConfiguration.hook }}
    "helm.sh/hook-weight": {{ (sub .Values.hookConfiguration.hookWeight 1) | quote }}
    "helm.sh/hook-delete-policy": {{ .Values.hookConfiguration.hookDeletePolicy }}
data:
  {{ base (.Values.secretPathOverride | default "/config/vault-actions.yaml") }}: |
    {{- with .Values.config }}
    {{- toYaml . | b64enc | nindent 4 }}
    {{- end }}
{{- end}}