{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vault-actions.serviceAccountName" . }}
  labels:
    {{- include "vault-actions.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": {{ .Values.hookConfiguration.hook }}
    "helm.sh/hook-weight": {{ .Values.hookConfiguration.hookWeight | quote }}
    "helm.sh/hook-delete-policy": {{ .Values.hookConfiguration.hookDeletePolicy }}
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
