name: create-release

on:
  repository_dispatch:
    types:
      - build-image-success

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          allowUpdates: true
          tag: ${{ github.event.client_payload.tag }}
          # artifacts: "release-*-*/*.tar.gz"
          # bodyFile: release_notes/${{ env.FABRIC_VER }}.md
          # bodyFile: "body.md"
          # artifacts: '*.pdf'
